### ISSUE TITLE
无法创建游戏窗口？

### ISSUE THREAD

**Issue by Tungstend** [AOF-Dev/lwjgl3-boat#2]
![468F75686AF7DFBFB2B4113A3C1B565C](https://user-images.githubusercontent.com/74163103/163127265-f4d9306c-058c-4579-99d8-855581f12c41.JPG)
我们编译了此lwjgl，并且配合glfw3.3进行测试，遇到了此报错

**Comment by CosineMath** [comment]
显然是因为未能加载egl。请确认添加了`mesa egl`或`gl4es egl wrapper`。egl库的文件名是`libEGL.so.1`，不要直接使用Android系统自带的egl。另外在Android端请显式调用`LoadMe.dlopen`加载库以绕开Android系统的限制。

**Comment by Tungstend** [comment]
这个egl库和Android自带的egl库有什么区别吗，Android自带的egl有被加载但是和glfw那些文件不在同一个命名空间，如果直接dlopen则需要一堆依赖，但是使用旧版lwjgl不单独加载egl就不会报错

**Comment by CosineMath** [comment]
egl库和gl库是配套的，比如mesa配套提供了两个库。使用gl4es理论上也需要这样一个配套的egl库。过去是直接在lwjgl/glfw里写兼容代码，把Android的egl当成适用于gl的来用，但是这样代码很不好看。去年为了支持mesa zink就改了，无论是gl4es还是mesa形式上都改成两个库（所以引入了gl4es egl wrapper）。这样更规范，而且一套lwjgl/glfw就可以同时支持他们，更容易维护。

**Comment by CosineMath** [comment]
手动dlopen并处理依赖目前是Android linker所逼的。除非全部so打进apk不然总有一些库需要手动dlopen。日后进一步hack可能会改善。

**Comment by Tungstend** [comment]
请问这个配套的egl库从哪里来？

**Comment by CosineMath** [comment]
当然是编译mesa或gl4es啊。。。

**Comment by Tungstend** [comment]
编译gl4es只有libGL.so啊。。是不是要改点什么在编译

**Comment by CosineMath** [comment]
你CMakeLists.txt看看不就知道了。。。

`option(EGL_WRAPPER "Set to ON to build EGL wrapper" ${EGL_WRAPPER})`

**Comment by Tungstend** [comment]
问题已解决，感谢

**Comment by Tungstend** [comment]
真不好意思，我又来了，gl4es启动1.17的时候默认检测opengl版本为2.1，然后直接退了，是否有办法谎报opengl版本用gl4es启动1.17？

**Comment by CosineMath** [comment]
上游的gl4es无法运行1.17+的。你需要使用[这个](https://github.com/AOF-Dev/gl4es)，并配置为启用glslang进行shader转换。可以参考一下我自己玩1.18.1用的配置文件：

```
[
    //[ "setenv", "LIBGL_MIPMAP", "3" ],
    //[ "setenv", "LIBGL_NORMALIZE", "1" ],
    [ "setenv", "LIBGL_GL", "32" ],
    [ "setenv", "LIBGL_ES", "3" ],
    [ "setenv", "LIBGL_SHADERCONVERTER", "1" ],
    
    [ "dlopen", "${runtime_path}/gl4es-glslconv/libglslang.so.11" ],
    [ "dlopen", "${runtime_path}/gl4es-glslconv/libglslconv.so" ],
    
    [ "dlopen", "${runtime_path}/gl4es-glslconv/libGL.so.1" ],
    [ "dlopen", "${runtime_path}/gl4es-glslconv/libEGL.so.1" ],
    
    [ "strcat", "library_path", 
        "${runtime_path}/gl4es-glslconv:",
    ],
]
```

当然glslang shader转换器不是很完善，不过运行原版应该没问题，我自己玩了挺长时间了。

**Comment by Tungstend** [comment]
这个libglslconv.so是怎么编译的，仓库里只有一个文件

**Comment by CosineMath** [comment]
`aarch64-linux-android21-clang glslconv.cpp -I /home/cosine/projects/glslang/glslang-build/aarch64-android-install/include/ -L /home/cosine/projects/glslang/glslang-build/aarch64-android-install/lib/ -lglslang -lc++ -shared -fPIC -Wl,--soname=libglslconv.so -o aarch64-android/lib/libglslconv.so`

当然首先你得编译[glslang shader converter](https://github.com/AOF-Dev/glslang-converter)

**Comment by Tungstend** [comment]
呃，启动是能启动了，但是用glfw打印分辨率会打印两次，一次正常一次犯病，而且可能会因为分辨率异常导致闪退或者无法控制
![3~X@DFK})J8W0MBOK8HA$MI](https://user-images.githubusercontent.com/74163103/163550051-608d262b-8a15-4061-9502-f25869f16688.png)

**Comment by Tungstend** [comment]
以及在另一些手机上居然会红屏加载不出画面，但是又能正常点击进世界，进入世界操作也正常，就是一片空白

**Comment by CosineMath** [comment]
。。。（我也不清楚你具体环境怎么配置的啊）


为什么打印两次分辨率呢？分别在什么时机打印的？


> 以及在另一些手机上居然会红屏加载不出画面，但是又能正常点击进世界，进入世界操作也正常，就是一片空白


首先你得确保你的环境运行1.16.5没有问题，然后**只替换**gl4es为带有glslang转换器的版本去启动1.18.1。

**Comment by CosineMath** [comment]
（另外由于没有用户很多东西都是只有我自己的设备测试过，有问题是很正常的，调试就是了。。。）

**Comment by Tungstend** [comment]
确实差异很大。。现在大家测试下来都没问题，只有我们开发者有问题。。。1.16确实是没问题的

**Comment by CosineMath** [comment]
。。。（你还没回答我前面提出的两个问题）

什么意思？普通用户能用你不能用？

**Comment by Tungstend** [comment]
是的。。还有分辨率问题解决了，啥也没动，卸载重装就好了。。

**Comment by Tungstend** [comment]
现在就剩我一个人红屏没解决，别人都没问题了。。

**Comment by CosineMath** [comment]
。。。你问问他们手机gpu是什么型号的？再看看自己手机是什么型号的。

（必须要支持gles 3.0才能用，我是mali-g76）

**Comment by Tungstend** [comment]
额，我888不太可能不支持吧，扩大了一下测试范围，好像出问题的基本都是绿厂的机子

**Comment by Tungstend** [comment]
刚刚又获取了一下gles版本，3.2，肯定没问题

**Comment by Tungstend** [comment]
蓝绿厂真是一家人，红屏的全是originos和coloros

**Comment by CosineMath** [comment]
。。。我也没有蓝绿的机子啊，没办法。你可否截几张图我看看？

**Comment by Tungstend** [comment]
进入游戏后操作正常就是没有画面，图一是游戏主界面，图二是进入世界之后。后面两张图我不知道是否和这个bug有关
![MJV5_$(949XSZ5KJG1G2%{P](https://user-images.githubusercontent.com/74163103/163567016-3754717c-fae1-4f64-8348-af29ffdd695e.jpg)
![6)L`P}0LIQCP@C`TPGMT_SB](https://user-images.githubusercontent.com/74163103/163567024-4fde3704-0564-49fd-8fbe-e344f46f75c3.jpg)
![}C$L%5OVEI8DB7}07GS70MC](https://user-images.githubusercontent.com/74163103/163567033-bc38f9f0-2869-455d-9f40-9a3f0f14c00e.jpg)
![1@GH~9OI1)BB (6F``RHMEL](https://user-images.githubusercontent.com/74163103/163567040-c4d0976f-62c3-4465-834c-1e907a79da32.jpg)

**Comment by CosineMath** [comment]
`OpenGL30 was reported as available but an entry point is missing`
这一个值得注意，我运行起来没有报这个错误。你可能需要调试一下到底是什么东西missing

那个jna不影响这个。

还有后面`Shader blit_screen could not find uniform named XXX`，这个错误我这里也没有。你可能需要调试一下shader转换器。你运行的是 1.17.1或1.18.1吗？

另外，为什么你的gl4es是libGL112.so，不会是gl4es 1.1.2吧。。。我用的是[这个](https://github.com/AOF-Dev/gl4es)的最后一个提交。

**Comment by Tungstend** [comment]
我只有启动1.17+版本才会出现这种情况，gl4es用的就是你那个，只不过之前用的1.1.2懒得改名，我再去看下转换器吧

**Comment by CosineMath** [comment]
你可以试着在gl4es的GetProc中打印一下信息看看是什么函数缺少。gl4es有个环境变量加上会打印转换前和转换后的shader，可能有帮助。另外你可以找他们要一下日志和自己的对照一下。祝你好运。。。

**Comment by Tungstend** [comment]
这。。
![-34053ba5557b4a61](https://user-images.githubusercontent.com/74163103/163575872-e96cde2b-a96e-48ce-9591-4f657749f7d6.jpg)

**Comment by Tungstend** [comment]
啊这。。这个应该不重要，正常的日志也有

**Comment by CosineMath** [comment]
你觉得没问题那就好。。。
