### ISSUE TITLE
如何适配多构架

### ISSUE THREAD

**Issue by Tungstend** [AOF-Dev/lwjgl3-boat#3]
如何适配armv7/x86/x86_64平台，尽管国内大多数用户都是armv8平台，但是仍有一小部分钉子户还是32位，国外更是寄，好多32位用户，而且有很多奇怪的设备比如chrome book

**Comment by CosineMath** [comment]
直接拿对应的交叉编译器编译就好了。最早这套东西就是用于32位arm的，因为我换了64位的手机就改用aarch64了。对于x86_64你可能需要自己处理一下动态链接库加载不了的问题。

**Comment by Tungstend** [comment]
好，我试试

**Comment by Tungstend** [comment]
那个openal怎么编译的，为啥我编译出来十几mb，之前用的都是3mb

**Comment by Tungstend** [comment]
![image](https://user-images.githubusercontent.com/74163103/187890294-d55172a5-c934-4032-b1a5-1d623a5f8fd9.png)
还有x86_64。。找不到egl

**Comment by CosineMath** [comment]
我哪记得大小，能用就行。你这图上怎么写的是arm64啊，还有库的后缀名.dll明显错了。前面我说了“对于x86_64你可能需要自己处理一下动态链接库加载不了的问题。”

**Comment by Tungstend** [comment]
![image](https://user-images.githubusercontent.com/74163103/187897970-354b285c-f74c-43f9-948d-cd9d6605fbc9.png)
截错图了。。那个dll报错，再arm64上也有，但是一点事也没有，顺便问下动态链接库的问题怎么解决呢，改那个patchlinker吗

**Comment by CosineMath** [comment]
那这样说，你这截图也没提供任何信息啊。我这里肯定是dlopen都不报错的。patch linker目前只适用于aarch64，这个你看代码也知道。对于x86_64你*可能*需要改类似的patch，具体怎么改我也不知道。

**Comment by CosineMath** [comment]
EGL not found，那么你应该去glfw的对应代码加点printf抓点信息。

**Comment by Tungstend** [comment]
找到问题了，egl解决了，但是还是有问题
![image](https://user-images.githubusercontent.com/74163103/187906429-adf9dc98-c20c-4414-94c3-d418a9f88acf.png)

**Comment by CosineMath** [comment]
很显然我帮不上什么忙，毕竟设备和代码在你手上。你需要自行调试lwjgl。

**Comment by Tungstend** [comment]
![-4903f418d5ff7b0d](https://user-images.githubusercontent.com/74163103/188110385-ed5ab5d6-1171-46e8-b5b2-4b9b6a765688.jpg)
![Screenshot_2022-09-02-17-32-09-40_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/74163103/188110405-aad55c00-e52d-4aae-a368-f25409d72d5e.jpg)
X86_64跑1.16.5成功了，但是openal还是有问题，我自己编译的x86_64没啥问题，arm64就没有声音

**Comment by Tungstend** [comment]
![~ 35A8N1_MXS)$FE0PXT)W](https://user-images.githubusercontent.com/74163103/188161536-8aca8c00-c2db-44cc-acfa-b68ccbc9d148.png)
其他都解决了，就差这个动态链接库的问题了，完全不知道咋解决，请问一下arm64那个patchlinker是怎么修的，确实连arm64的都没看懂

**Comment by CosineMath** [comment]
我简单跟你说一下吧。这个错误是因为，Android 7.0以后，64位linker添加了某种**无聊（可恶）的保护机制**。只有打包在apk/libs下面的那些.so才能被顺利地dlopen，也只有它们才能顺利dlopen其它.so库。我们的运行环境的lwjgl，jdk之类的虽然放在内部私有目录，也*不能*良好地dlopen放在私有目录的libglfw.so。所以我写了个patchLinker，在加载我们的运行环境之前，先把aarch64的linker中的dlopen、dlsym、dlvsym这三个函数的代码改掉。具体来说就是伪装成libloadme.so去调用dlopen，从而绕开这个**无聊（可恶）的保护机制**。32位没有这个**无聊（可恶）的保护机制**，所以不用patch。
至于解决方法，简单来说就是不要让dlopen的内部实现知道函数调用者是lwjgl或jdk。
你可以参考aarch64的patchLinker为x86_64写一个类似的；也可以加一个库libsubstrate.so，用这个库提供hook去改dlopen的执行流程；还可以在libloadme.so加一个dlopen_wrapper函数，然后lwjgl、jdk等各处调用dlopen的地方改成用dlopen_wrapper（最后这个方法不推荐）。

**Comment by Tungstend** [comment]
感谢，但是为什么最后一个不推荐呢

**Comment by Tungstend** [comment]
动态库加载的问题好像是解决了，但是x86_64设备上glfw还是有问题，报错貌似是这个函数报的
![image](https://user-images.githubusercontent.com/74163103/190895877-30bb1244-c8d5-4f61-9b4c-f7a6b1440e9c.png)
![image](https://user-images.githubusercontent.com/74163103/190895885-cc726eeb-ed5c-43e6-9975-78fa8f665770.png)

**Comment by Tungstend** [comment]
很怪，as的虚拟机上一点问题没有，上了真机就不行了

**Comment by Tungstend** [comment]
最终移除了patchlinker，确实是命名空间问题，glfw初始化的时候获取不到nativewindow，具体什么时候会触发这个bug我至今也没搞明白，但是在一些鸿蒙和x64机型上尤其常见，我的解决办法是把启动器这边设置好的环境setenv保存在环境变量里，再次加载libboat的时候从环境变量里取配置，另外还需要在glfw里dlopen对应的渲染否则还是不在同一命名空间
